import { NextResponse } from "next/server";

export async function GET() {
  const hotspots = [
    {
      id: "h1",
      rank: 1,
      name: "Ward 4 - Main St",
      reportsCount: 18,
      avgAge: "3d old",
      urgency: "critical",
      lat: 23.234158,
      lng: 72.500038,
      description: "5 active issues, frequent road craters and water main leakages",
      categories: ["pothole", "water leak", "streetlight", "drain"],
    },
    {
      id: "h2",
      rank: 2,
      name: "Market Square",
      reportsCount: 12,
      avgAge: "1d old",
      urgency: "high",
      lat: 23.238910,
      lng: 72.505412,
      description: "Severe pipeline leakage disrupting pedestrian market stalls",
      categories: ["water leak", "pothole"],
    },
    {
      id: "h3",
      rank: 3,
      name: "Metro Gate 2",
      reportsCount: 9,
      avgAge: "6h old",
      urgency: "medium",
      lat: 23.229870,
      lng: 72.495120,
      description: "Streetlights dark across entire transit footway corridor",
      categories: ["streetlight"],
    },
    {
      id: "h4",
      rank: 4,
      name: "Civil Lines Crossroad",
      reportsCount: 7,
      avgAge: "12h old",
      urgency: "medium",
      lat: 23.241500,
      lng: 72.512200,
      description: "Stormwater grate clogged causing wastewater spill onto junction",
      categories: ["drain"],
    },
    {
      id: "h5",
      rank: 5,
      name: "Heritage Colony",
      reportsCount: 5,
      avgAge: "2d old",
      urgency: "low",
      lat: 23.225100,
      lng: 72.489300,
      description: "Asphalt subsidence near residential entry Gate 1",
      categories: ["pothole"],
    },
  ];

  // Lightweight marker objects for high-performance rendering & clustering
  const markers = [
    {
      id: "CIGA-849201-412",
      title: "Deep Pothole at Junction",
      category: "pothole",
      status: "pending",
      isUrgent: true,
      isOverdue: true,
      lat: 23.234158,
      lng: 72.500038,
      locationName: "Ward 4 - Main St",
    },
    {
      id: "CIGA-732104-981",
      title: "Streetlight Fixture Dark",
      category: "streetlight",
      status: "processing",
      isUrgent: false,
      isOverdue: false,
      lat: 23.23439,
      lng: 72.50025,
      locationName: "Ward 4 - Main St",
    },
    {
      id: "CIGA-884912-301",
      title: "Underground Water Leak",
      category: "water leak",
      status: "pending",
      isUrgent: true,
      isOverdue: false,
      lat: 23.23395,
      lng: 72.49982,
      locationName: "Ward 4 - Main St",
    },
    {
      id: "CIGA-772910-442",
      title: "Broken Stormwater Drain Grate",
      category: "drain",
      status: "processing",
      isUrgent: false,
      isOverdue: false,
      lat: 23.23452,
      lng: 72.49971,
      locationName: "Ward 4 - Main St",
    },
    {
      id: "CIGA-661902-881",
      title: "Secondary Road Surface Crack",
      category: "pothole",
      status: "completed",
      isUrgent: false,
      isOverdue: false,
      lat: 23.23402,
      lng: 72.50041,
      locationName: "Ward 4 - Main St",
    },
    {
      id: "CIGA-551982-101",
      title: "Market Water Main Seepage",
      category: "water leak",
      status: "pending",
      isUrgent: true,
      isOverdue: true,
      lat: 23.238910,
      lng: 72.505412,
      locationName: "Market Square",
    },
    {
      id: "CIGA-441829-221",
      title: "Metro Gate 2 Streetlight Dark",
      category: "streetlight",
      status: "processing",
      isUrgent: false,
      isOverdue: false,
      lat: 23.229870,
      lng: 72.495120,
      locationName: "Metro Gate 2",
    },
    {
      id: "CIGA-331702-774",
      title: "Civil Lines Drain Overflow",
      category: "drain",
      status: "pending",
      isUrgent: true,
      isOverdue: false,
      lat: 23.241500,
      lng: 72.512200,
      locationName: "Civil Lines Crossroad",
    },
    {
      id: "CIGA-221601-998",
      title: "Heritage Colony Asphalt Sinkhole",
      category: "pothole",
      status: "processing",
      isUrgent: false,
      isOverdue: false,
      lat: 23.225100,
      lng: 72.489300,
      locationName: "Heritage Colony",
    },
  ];

  return NextResponse.json({
    success: true,
    totalCount: markers.length,
    hotspots,
    markers,
  });
}
